### ISSUE TITLE
Can't reach gemstash

### ISSUE THREAD

**Issue by zedtux** [Intellection/docker-gemstash#2]
First of all, very beautiful Dockerfile and stuff 👍.

So I started the Docker container as the following:

```bash
docker run --publish=9292:9292 zappi/gemstash:1.1.0
WARNING: Tini has been relocated to /sbin/tini.
Please update your scripts to use /sbin/tini going forward.
/usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
but WILL BE REMOVED in Alpine 3.5.

Starting gemstash!
[2018-02-23 08:05:09 +0000] - INFO - [11] Puma starting in cluster mode...
[2018-02-23 08:05:09 +0000] - INFO - [11] * Version 2.16.0 (ruby 2.4.1-p111), codename: Midwinter Nights Trance
[2018-02-23 08:05:09 +0000] - INFO - [11] * Min threads: 0, max threads: 0
[2018-02-23 08:05:09 +0000] - INFO - [11] * Environment: development
[2018-02-23 08:05:09 +0000] - INFO - [11] * Process workers: 1
[2018-02-23 08:05:09 +0000] - INFO - [11] * Phased restart available
[2018-02-23 08:05:09 +0000] - INFO - [11] * Listening on tcp://0.0.0.0:9292
[2018-02-23 08:05:09 +0000] - INFO - [11] Use Ctrl-C to stop
[2018-02-23 08:05:09 +0000] - INFO - [11] - Worker 0 (pid: 13) booted, phase: 0
```

But when I try to access it:

```bash
curl -vv http://localhost:9292
* Rebuilt URL to: http://localhost:9292/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
> GET / HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.54.0
> Accept: */*
>

```

And nothing happen. Can you please help me to figure out what is going wrong?

**Comment by zacblazic** [comment]
Hi @zedtux, thanks for the feedback. 

We've addressed this issue in 1.2.0 (#3), please could you give the version a go?

Note that you can use `/health` to check the status of Gemstash:
```
$ curl localhost:9292/health
{"status":{"heartbeat":"OK","storage_read":"OK","storage_write":"OK","db_read":"OK","db_write":"OK"}}
```

**Comment by zedtux** [comment]
@zacblazic I confirm it is better working now 👍.

Nonetheless I'm trying to use this container in order to get a faster `docker-compose build`  command but while the `curl` command is working on my host, the `bundle install` command is failing with `docker-compose build` with

```bash
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for "localhost" port 9292
  /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
  /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `open'
  /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
  /usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
  /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call'
  /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
  /usr/local/lib/ruby/2.2.0/net/http.rb:878:in `connect'
  /usr/local/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
  /usr/local/lib/ruby/2.2.0/net/http.rb:858:in `start'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:702:in `start'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:633:in `connection_for'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendored_persistent.rb:23:in `connection_for'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:996:in `request'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/fetcher/downloader.rb:51:in `request'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/fetcher/downloader.rb:17:in `fetch'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/fetcher/compact_index.rb:117:in `call'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:51:in `block in update'
  /usr/local/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:31:in `update'
  ...
```

Do you know I could handle this error?

**Comment by zacblazic** [comment]
FYI, I've re-created the 1.1.0 tag, and removed the 1.2.0 tag to [keep the version aligned](https://github.com/Intellection/docker-gemstash/pull/4) with Gemstash.

About your issue...
> Nonetheless I'm trying to use this container in order to get a faster docker-compose build command but while the curl command is working on my host, the bundle install command is failing with docker-compose build with
>```
>Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for "localhost" port 9292
>  /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
>  /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `open'
>  /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
>  /usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
>  /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call'
>  /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
>  /usr/local/lib/ruby/2.2.0/net/http.rb:878:in `connect'
>  /usr/local/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
>  /usr/local/lib/ruby/2.2.0/net/http.rb:858:in `start'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:702:in `start'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:633:in `connection_for'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendored_persistent.rb:23:in `connection_for'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:996:in `request'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/fetcher/downloader.rb:51:in `request'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/fetcher/downloader.rb:17:in `fetch'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/fetcher/compact_index.rb:117:in `call'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:51:in `block in update'
>  /usr/local/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
>  /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:31:in `update'
>  ...
>```

It seems to be that you're trying to re-use the `9292` port. Do you perhaps have another instance of the container running in the background?

The quick-setup way to use Gemstash is as follows..

Start the container:
```
$ docker run --publish=9292:9292 zappi/gemstash:1.1.0
Starting gemstash!
[2018-02-23 18:16:20 +0000] - INFO - [9] Puma starting in cluster mode...
[2018-02-23 18:16:20 +0000] - INFO - [9] * Version 2.16.0 (ruby 2.5.0-p0), codename: Midwinter Nights Trance
[2018-02-23 18:16:20 +0000] - INFO - [9] * Min threads: 0, max threads: 16
[2018-02-23 18:16:20 +0000] - INFO - [9] * Environment: development
[2018-02-23 18:16:20 +0000] - INFO - [9] * Process workers: 1
[2018-02-23 18:16:20 +0000] - INFO - [9] * Phased restart available
[2018-02-23 18:16:20 +0000] - INFO - [9] * Listening on tcp://0.0.0.0:9292
[2018-02-23 18:16:20 +0000] - INFO - [9] Use Ctrl-C to stop
[2018-02-23 18:16:20 +0000] - INFO - [9] - Worker 0 (pid: 11) booted, phase: 0
```

Configure bundler to use your local gemstash container as a mirror:
```
bundle config mirror.https://rubygems.org http://localhost:9292
```

Then bundle, and you should see activity in the logs of the gemstash container:
```
[2018-02-23 18:18:06 +0000] - INFO - [11] 172.17.0.1 - - [23/Feb/2018:18:18:06 +0000] "GET /versions HTTP/1.1" 302 - 0.0091
[2018-02-23 18:18:07 +0000] - INFO - [11] 172.17.0.1 - - [23/Feb/2018:18:18:07 +0000] "GET /api/v1/dependencies HTTP/1.1" 200 - 0.0009
[2018-02-23 18:18:07 +0000] - INFO - Fetching dependencies: actionmailer, actionpack, actionview, active_model_serializers, activejob, activemodel, activerecord, activesupport, addressable, annotate, arel, ast, attribute_normalizer, autoprefixer-rails, awesome_print, bcrypt, better_errors, bootstrap-sass, brakeman, builder, bullet, bundler-audit, case_transform, coderay, concurrent-ruby, crass, erubis, execjs, globalid, i18n, jsonapi-renderer, loofah, mail, mime-types, mime-types-data, mini_portile2, minitest, nokogiri, public_suffix, rack, rack-test, rails-deprecated_sanitizer, rails-dom-testing, rails-html-sanitizer, rake, sass, thor, thread_safe, tzinfo, uniform_notifier
```

**Comment by zedtux** [comment]
@zacblazic thank you for your comment, but you missed the point of my issue. I'm using Docker in order to build my app's image with `docker-compose build`.

What I'm trying to achieve is to have this `docker-compose build` being much more faster on the `bundle install` command step.
My guess was to have the following:

1. Start a gemstash server on my host
2. Run the Docker build command
3. Changes the Bundler proxy from the Dockerfile
4. At the step where I'm running `bundle install` I was expecting `bundler` from within the image to connect to the `localhost:9292` but since I have this `bundle config mirror.https://rubygems.org http://localhost:9292` in my Dockerfile it is like it is trying to open a server while I'm expecting to use `http://localhost:9292` as the source for my `Gemfile` instead of `https://rubygems.org`.

BTW I have the same error no matter gemstash is running or not so it's like Docker doesn't allow Bundler to start a server on that port.

**Comment by zedtux** [comment]
Actually I just realise that all-in-all, gemstash will not help me because the longest gem to install is coming from a Github repo so it is out of the scope of gemstash ...

I have to look for a more general proxy software.

I'm closing this issue then.

Anyway thank you @zacblazic for your assistance 👍

**Comment by zacblazic** [comment]
No problems. 

Just for future reference, I think your issue is that you're expecting `localhost:9292` on the docker host to be visible inside the container which won't be the case unless you're using `--net=host` when running the container.

For more details see [this post](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach).

**Comment by zedtux** [comment]
Yep, and someone has explained it step-by-step on [my SO question](https://stackoverflow.com/questions/48950762/connection-refused-to-a-local-container-while-running-doingdocker-compose-bui/48968554#48968554).

Thank you @zacblazic.
